# List VS Numpy : 
## Lsits very slow while Numpy very fast.
1. Numpy the type are the same; and faster to read less bytes of memory
*  numpy use continous memory so it is faster to read
** benefit: SIMD Vector processing 
** benefit: Effective Cache Utilization
2. no type checking when read interration objects
# List and Numpy could do insert.delete,append,concatenation,etc
#### https://www.youtube.com/watch?v=QUT1VHiLmmI

In [ ]:
import numpy as np

In [1]:
a=[1,2,3]
b=[4,5,6]
a*b  ##error

TypeError: can't multiply sequence by non-int of type 'list'

In [5]:
a=np.array([1,2,3]) # 1 - dimension
b=np.array([4,5,6])
a*b

array([ 4, 10, 18])

In [6]:
a

array([1, 2, 3])

In [7]:
print(a)

[1 2 3]


In [10]:
# 2 - dimensional float
b=np.array([[1.,2.,3.],[4.,5.,6.]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [11]:
# Get dimension
a.ndim

1

In [12]:
b.ndim

2

In [13]:
a.shape

(3,)

In [14]:
b.shape

(2, 3)

In [15]:
# get type (default : int32)
a.dtype

dtype('int32')

In [17]:
a=np.array([1,2,3],dtype='int16') #specify the dtype

In [18]:
a.dtype

dtype('int16')

In [19]:
a.itemsize  #bytes 

2

In [20]:
a=np.array([1,2,3],dtype='int32') #specify the dtype
a.itemsize 

4

In [23]:
print(b.dtype)
print(b.itemsize)
print(a.size * a.itemsize)
print(b.size * b.itemsize)

float64
8
12
48


In [ ]:
## Applciaiton of numpy
* Mathematics(MATLAB replacement)
* Plotting(matplotlib)
* Backend(Pandas - Core ,numpy to store photo)
* machine learning

In [ ]:
## accessing/changing specific elements.rows/columns

In [24]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [26]:
#get one element [r,c]
a[1,5]

13

In [27]:
a[1,-2]

13

In [28]:
#get a specific row
a[0,]

array([1, 2, 3, 4, 5, 6, 7])

In [29]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
#get a specific column
a[:,3]

array([ 4, 11])

In [34]:
# [startIndex:endIndex: stepsize]  endIndex is exclusive （不包含）
a[0,1:6:2]

array([2, 4, 6])

In [36]:
a[0,1:-1:2] 

array([2, 4, 6])

In [37]:
a[1,5]=1300
print(a)

[[   1    2    3    4    5    6    7]
 [   8    9   10   11   12 1300   14]]


In [38]:
#modify the column values
a[:,2]=200
print(a)

[[   1    2  200    4    5    6    7]
 [   8    9  200   11   12 1300   14]]


In [39]:
a[:,2]=[2,2]
print(a)

[[   1    2    2    4    5    6    7]
 [   8    9    2   11   12 1300   14]]


In [42]:
## 3-d example

In [43]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [44]:
c.shape

(2, 2, 2)

In [45]:
c.dtype

dtype('int32')

In [46]:
c.itemsize #bytes 

4

In [47]:
c.size

8

In [48]:
# Get specific element (from outside to inside) of 3-d 
c[0,1,1] 

4

In [49]:
c[:,1,:]

array([[3, 4],
       [7, 8]])

In [50]:
c[:,:,0]

array([[1, 3],
       [5, 7]])

In [53]:
#change some value
c[:,1,:]=[[6,6],[9,9]]
print(c)

[[[1 2]
  [6 6]]

 [[5 6]
  [9 9]]]


In [ ]:
# Initializing different type of arrays

In [56]:
t1 = np.zeros(5)

In [57]:
t1.dtype

dtype('float64')

In [58]:
t1.itemsize

8

In [61]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [62]:
#all 1s matrix
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [63]:
np.ones((2,2,2)).dtype

dtype('float64')

In [64]:
#specific the dtype
np.ones((2,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [65]:
#any other number 
np.full((2,2),100)

array([[100, 100],
       [100, 100]])

In [66]:
#any other number（full like）,like other numpy 's shape
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [67]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [70]:
#random decimal numbers
np.random.rand(2,2,4)

array([[[0.54869233, 0.89052687, 0.1259932 , 0.3527456 ],
        [0.8061531 , 0.77833567, 0.41901373, 0.00331255]],

       [[0.58233282, 0.70915988, 0.95102167, 0.97574426],
        [0.39795207, 0.38129529, 0.58999256, 0.50582088]]])

In [71]:
np.random.random_sample(a.shape)

array([[0.4553539 , 0.59570778, 0.67569177, 0.70774178, 0.70006181,
        0.95785516, 0.63467329],
       [0.68149685, 0.83032841, 0.5621292 , 0.20553922, 0.43963269,
        0.121765  , 0.16560747]])

In [74]:
#random integer values
np.random.randint(5,size=(3,3)) 

array([[4, 3, 2],
       [3, 4, 2],
       [4, 3, 3]])

In [75]:
np.random.randint(2,4,size=(3,3)) #startvalue :endvalue(exclusive 不包含)

array([[2, 3, 3],
       [2, 2, 3],
       [3, 3, 2]])

In [76]:
np.identity(5) #identify matrix 单位矩阵

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [77]:
np.identity(5).dtype

dtype('float64')

In [78]:
#repeat an array
arr=np.array([1,2,3])
r1=np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [82]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
##Quick test

In [92]:
output = np.ones((5,5),dtype='int32')
print(output)

z= np.zeros((3,3))
z[1,1]=9

#output[1:4,1:4]=z
output[1:-1,1:-1]=z
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [94]:
##be carefull when copy!!!!! ；use b=a change b lead to the change of a as well
a= np.array([1,2,3])
b=a
b[0]=1000
print(b)
print(a)

[1000    2    3]
[1000    2    3]


In [96]:
#should use a.copy
a= np.array([1,2,3])
b=a.copy()
b[0]=1000
print(b)
print(a)

[1000    2    3]
[1 2 3]


In [ ]:
#matthematics

In [97]:
a = np.array([1,2,3,4])


In [98]:
a + 2

array([3, 4, 5, 6])

In [99]:
a- 2

array([-1,  0,  1,  2])

In [100]:
a * 2

array([2, 4, 6, 8])

In [101]:
a / 2 

array([0.5, 1. , 1.5, 2. ])

In [102]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [103]:
a.dtype

dtype('int32')

In [110]:
a ** 2  #pwoer function

array([ 1,  4,  9, 16], dtype=int32)

In [107]:
# take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

#### Linear Algebra

In [114]:
a = np.ones((2,3))
print(a)

b=np.full((3,2),3)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]]


In [115]:
#matrix mul 矩阵乘法
np.matmul(a,b)

array([[9., 9.],
       [9., 9.]])

![det.jpg](attachment:det.jpg)

In [116]:
#find the determinant
c=np.identity(3)
np.linalg.det(c)

1.0

#### statistics

In [118]:
stat= np.array([[1,2,3],[4,5,6]])
stat

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
np.min(stat)

1

In [120]:
np.min(stat,axis=1) #row

array([1, 4])

In [121]:
np.min(stat,axis=0) #column


array([1, 2, 3])

In [122]:
np.max(stat,axis=1) 

array([3, 6])

In [123]:
np.sum(stat)

21

In [125]:
np.sum(stat,axis=0)

array([5, 7, 9])

In [126]:
np.sum(stat,axis=1)

array([ 6, 15])

### reorganizing arrays

In [129]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after= before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### Vertically stacking vectors

In [131]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2])
np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

#### horizontal stack

In [135]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


In [133]:
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#### load data from file

In [138]:
filedata = np.genfromtxt('data.txt',delimiter=',')
filedata.dtype

dtype('float64')

In [139]:
filedata.astype('int32')

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [140]:
filedata

array([[1., 2., 3., 4., 5., 6., 7., 8.],
       [1., 2., 3., 4., 5., 6., 7., 8.],
       [1., 2., 3., 4., 5., 6., 7., 8.],
       [1., 2., 3., 4., 5., 6., 7., 8.]])

In [141]:
filedata = filedata.astype('int32')

In [142]:
filedata

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

#### Boolean masking and advanced indexing

In [144]:
filedata>5

array([[False, False, False, False, False,  True,  True,  True],
       [False, False, False, False, False,  True,  True,  True],
       [False, False, False, False, False,  True,  True,  True],
       [False, False, False, False, False,  True,  True,  True]])

In [145]:
filedata[filedata>5]

array([6, 7, 8, 6, 7, 8, 6, 7, 8, 6, 7, 8])

In [149]:
np.any(filedata>3,axis=0) #column based, 按照列遍历所有的元素

array([False, False, False,  True,  True,  True,  True,  True])

In [150]:
np.all(filedata>3,axis=0)

array([False, False, False,  True,  True,  True,  True,  True])

In [151]:
((filedata>2)&(filedata<8))

array([[False, False,  True,  True,  True,  True,  True, False],
       [False, False,  True,  True,  True,  True,  True, False],
       [False, False,  True,  True,  True,  True,  True, False],
       [False, False,  True,  True,  True,  True,  True, False]])

In [152]:
(~((filedata>2)&(filedata<8)))

array([[ True,  True, False, False, False, False, False,  True],
       [ True,  True, False, False, False, False, False,  True],
       [ True,  True, False, False, False, False, False,  True],
       [ True,  True, False, False, False, False, False,  True]])

![quiz.jpg](attachment:quiz.jpg)